server:
  port: 8087

spring:
  application:
    name: posting
  datasource:
    url: jdbc:postgresql://localhost:5432/posting
    username: 'linkho'
    password: 'linkho'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true